### PR TITLE
Renamed some variables

### PR DESCRIPTION
**Pull request by mraaroncruz**

### CODE REVIEW

**Comment by dch** [comment]
image

tasty!

**Comment by dch** [comment]
thanks for that, I am going to need to work a bit more on it:

```
$ wsd -url='wss://riemann:5556/index?subscribe=true&query=(host ~= "mrbrown")'
panic: parse wss%3A%2F%2Friemann%3A5556%2Findex%3Fsubscribe%3Dtrue%26query%3D%28host+~%3D+%22mrbrown%22%29: invalid URI for request
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x11e94c6]

goroutine 1 [running]:
golang.org/x/net/websocket.(*Conn).Close(0x0, 0x2, 0x2)
	/repos/go/src/golang.org/x/net/websocket/websocket.go:236 +0x26
panic(0x122f340, 0xc420014ed0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
main.main()
	/repos/go/src/github.com/skunkwerks/wsd/main.go:127 +0xba3
 ~
```

the url-escaping is a bit ... overzealous.

**Comment by mraaroncruz** [comment]
Yeah, you can probably parse out the uri.
https://golang.org/pkg/net/url/#URL.Parse

**Comment by mraaroncruz** [comment]
That's a wild url, bruh

**Pull request merged**
